### PR TITLE
Feature/casmnet 2024  - Add additional loadbalancers to unbound for scaling

### PR DESCRIPTION
**Pull request by dle-hpe**
## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_
- Add additional loadbalancers to unbound for scaling
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ y

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

CSAMNET-2024
CAST-31858

## Testing

_List the environments in which these changes were tested._

### Tested on:

NERSC Muller
NERSC Perlmutter

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- manual testing with proper helm labels to allow upgrades and downgrades

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?n
- Were continuous integration tests run? If not, why?n
- Was upgrade tested? If not, why?y
- Was downgrade tested? If not, why?y
- Were new tests (or test issues/Jiras) created for this change?n

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_
- none

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [ ] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Review by trad511 — COMMENTED** [review]
Is it possible to create the usual single by default but have some override input for system scaling/sizing?

**Review by lukebates123 — APPROVED** [review]

**Review by trad511 — COMMENTED** [review]
This solution obviously works, but is this implementation guided chiefly by the issue exposed for a large system that cannot implement another fix?  Would this fix be different if the system could be re-installed from scratch?  I have reservations about holding this fix when it's never going to be required for smaller systems - ie. 99% of those in use - and root cause is client use, not server-side load.

**Comment by dle-hpe** [comment]
> 

I don't think it would be easy since there is no data source to use dynamically at chart deploy time.  IE: SLS assumes all cabinets are populated.

**Comment by dle-hpe** [comment]
Reason for additional loadbalancers is a workaround for a scaling issue to address:
- not able to rely only on single Loadbalancer set to Local like previous solution for large systems
- possible ecmp bug with bgp 8 peer limit on systems with more than 8 workers

**Pull request merged**
